#!/bin/sh
set -e
# [ "$UID" -eq 0 ] || exec sudo sh "$0" "$@"

MY_PATH=$(dirname "$0")
"$MY_PATH/pwnkit-ascii"

# Check for docker

echo "Pulling latest base image . . ."
docker pull kalilinux/kali-rolling:latest
echo "Base image pulled."

echo "Building docker image . . ."
docker build -t jasperboot/pwnkit:latest .
echo "Docker image built successfully."

# echo "Pushing new version to registry . . ."
# docker jasperboot/pwnkit:latest
# echo "New image pushed succesfully!"
