#!/bin/bash
set -e

IMAGE_NAME="pwnkit:latest"

MY_PATH=$(dirname "$(readlink -f "$0")")

echo "Pulling latest base image . . ."
docker pull kalilinux/kali-rolling:latest
echo "Base image pulled."

echo "Building docker image . . ."
docker build -t $IMAGE_NAME $MY_PATH
echo "Docker image built successfully."
